import type { CSSProperties } from 'react'

export const classicDarkStyle: Record<string, CSSProperties> = {
  'code[class*="language-"]': {
    color: '#e5e7eb',
    background: 'none',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    fontSize: '0.875rem',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    overflowWrap: 'normal',
    lineHeight: '1.6',
    tabSize: 4,
  },
  'pre[class*="language-"]': {
    color: '#e5e7eb',
    background: '#111827',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    fontSize: '0.875rem',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    overflowWrap: 'normal',
    lineHeight: '1.6',
    tabSize: 4,
    overflow: 'auto',
    margin: 0,
  },
  comment: { color: '#9ca3af', fontStyle: 'italic' },
  prolog: { color: '#9ca3af' },
  doctype: { color: '#9ca3af' },
  cdata: { color: '#9ca3af' },
  punctuation: { color: '#d1d5db' },
  property: { color: '#e5e7eb' },
  tag: { color: '#e5e7eb' },
  boolean: { color: '#f3f4f6' },
  number: { color: '#d1d5db' },
  constant: { color: '#d1d5db' },
  symbol: { color: '#d1d5db' },
  deleted: { color: '#9ca3af' },
  selector: { color: '#f3f4f6' },
  'attr-name': { color: '#e5e7eb' },
  string: { color: '#d1d5db' },
  char: { color: '#d1d5db' },
  builtin: { color: '#e5e7eb' },
  inserted: { color: '#e5e7eb' },
  operator: { color: '#9ca3af' },
  entity: { color: '#e5e7eb' },
  url: { color: '#d1d5db' },
  variable: { color: '#e5e7eb' },
  atrule: { color: '#e5e7eb' },
  'attr-value': { color: '#d1d5db' },
  function: { color: '#f3f4f6' },
  'class-name': { color: '#e5e7eb' },
  keyword: { color: '#f3f4f6', fontWeight: 500 },
  regex: { color: '#d1d5db' },
  important: { color: '#f3f4f6' },
}
